name: Handle issues
# on: [push,issues, workflow_dispatch]
on: [workflow_dispatch]
jobs:
  output-info:
    runs-on: ubuntu-latest
    steps:
      - name: Output event details
        run: echo "${{ toJSON(github.event) }}"
